#include <systemc.h>
#include <chrono>
#include <iostream>
#include <fstream>
#include <stdexcept>

#include "config.h"
#include "files_manager.h"
#include "parser.h"
#include "vta.h"

int sc_main(int, char*[]) {
    auto& config = PlatformConfig::getInstance();
    FilesManager files_manager(config.granulatity, const_cast<char*>(config.model_name.c_str()));
    Parser parser(files_manager.model_path);

    VTA vta("vta", parser.keys, parser.encoded_splited_instructions);

    // --- LOAD dummy_data.bin INTO AXI SLAVE DRAM ---
    // dummy_data.bin contains pre-populated input/weight/uop/bias test data
    // generated by prepare_dummy_data.py. We overwrite the slave's zero-init
    // memory with this file so the simulation sees real (dummy) data.
    // The instruction region is written by vta.cpp's constructor, so it will
    // correctly overwrite whatever dummy_data.bin has there.
    {
        std::string dram_path = std::string(SOURCE_DIR) + "/data/models/dummy_data.bin";
        std::ifstream f(dram_path, std::ios::binary | std::ios::ate);
        if (f.is_open()) {
            std::streamsize sz = f.tellg();
            f.seekg(0, std::ios::beg);
            if ((size_t)sz <= vta.dram->memory_array.size()) {
                f.read(reinterpret_cast<char*>(vta.dram->memory_array.data()), sz);
                std::cout << "[DRAM] Loaded " << sz/(1024*1024) << " MB from dummy_data.bin" << std::endl;
            } else {
                std::cout << "[DRAM] dummy_data.bin (" << sz/(1024*1024) << " MB) exceeds DRAM size, skipping" << std::endl;
            }
        } else {
            std::cout << "[DRAM] dummy_data.bin not found - DRAM is random-initialized" << std::endl;
        }
    }

    // --- SETUP MEMORY (DUMP INSTRUCTIONS TO DRAM) ---

    // Fetcher start address from JSON configuration
    auto& sys_config = PlatformConfig::getInstance();
    uint32_t dram_offset = sys_config.instruction_base_addr;

    for (const auto& key : parser.keys) {
        for (const auto& instruction : parser.encoded_splited_instructions[key]) {
            uint64_t part0 = std::get<1>(instruction).to_uint64();
            uint64_t part1 = std::get<2>(instruction).to_uint64();

            // Write first 8 bytes
            for(int i = 0; i < 8; i++) {
                vta.dram->memory_array[dram_offset++] = (part0 >> (i * 8)) & 0xFF;
            }
            // Write second 8 bytes
            for(int i = 0; i < 8; i++) {
                vta.dram->memory_array[dram_offset++] = (part1 >> (i * 8)) & 0xFF;
            }
        }
    }

    // --- SETUP WAVEFORM TRACING ---
    sc_trace_file *tf = sc_create_vcd_trace_file("vta_waveforms");
    tf->set_time_unit(1, SC_NS);

    // ==========================================
    // 1. SYSTEM STATUS
    // ==========================================
    sc_trace(tf, vta.sys_clk,   "1_SYS/clk");
    sc_trace(tf, vta.sys_reset, "1_SYS/reset_n");
    sc_trace(tf, vta.compute_arm_trig, "1_SYS/FINISH_layer_done");

    // ==========================================
    // 2. FETCHER MODULE (Instruction Fetch)
    // ==========================================
    sc_trace(tf, vta.m3_ARVALID, "2_FETCHER/AXI_ARVALID");
    sc_trace(tf, vta.m3_ARREADY, "2_FETCHER/AXI_ARREADY");
    sc_trace(tf, vta.m3_ARADDR,  "2_FETCHER/AXI_ARADDR");
    sc_trace(tf, vta.m3_RVALID,  "2_FETCHER/AXI_RVALID");
    sc_trace(tf, vta.m3_RREADY,  "2_FETCHER/AXI_RREADY");
    sc_trace(tf, vta.m3_RDATA,   "2_FETCHER/AXI_RDATA");
    
    sc_trace(tf, vta.fetcher->trace_expected_part0, "2_FETCHER/VALIDATION_expected_part0");
    sc_trace(tf, vta.fetcher->trace_expected_part1, "2_FETCHER/VALIDATION_expected_part1");
    sc_trace(tf, vta.fetcher->trace_fetched_part0, "2_FETCHER/VALIDATION_fetched_part0");
    sc_trace(tf, vta.fetcher->trace_fetched_part1, "2_FETCHER/VALIDATION_fetched_part1");

    // --- 3. QUEUES / DISPATCH ---==========================================
    // 3. DISPATCH ROUTING (Fetcher -> Modules)
    // ==========================================
    sc_trace(tf, vta.fetcher_l_queue_vld_sig, "3_DISPATCH/to_LOAD_vld");
    sc_trace(tf, vta.l_queue_load_data,       "3_DISPATCH/to_LOAD_data");
    
    sc_trace(tf, vta.fetcher_c_queue_vld_sig, "3_DISPATCH/to_COMPUTE_vld");
    sc_trace(tf, vta.c_queue_compute_data,    "3_DISPATCH/to_COMPUTE_data");
    
    sc_trace(tf, vta.fetcher_s_queue_vld_sig, "3_DISPATCH/to_STORE_vld");
    sc_trace(tf, vta.s_queue_store_data,      "3_DISPATCH/to_STORE_data");

    // ==========================================
    // 4. LOAD MODULE (AXI Master 0)
    // ==========================================
    sc_trace(tf, vta.m0_ARADDR,  "4_LOAD/AXI_ARADDR");
    sc_trace(tf, vta.m0_ARVALID, "4_LOAD/AXI_ARVALID");
    sc_trace(tf, vta.m0_ARREADY, "4_LOAD/AXI_ARREADY");
    sc_trace(tf, vta.m0_RVALID,  "4_LOAD/AXI_RVALID");
    sc_trace(tf, vta.m0_RREADY,  "4_LOAD/AXI_RREADY");
    sc_trace(tf, vta.m0_RDATA,   "4_LOAD/AXI_RDATA");

    // ==========================================
    // 5. COMPUTE MODULE (AXI Master 1)
    // ==========================================
    sc_trace(tf, vta.m1_ARADDR,  "5_COMPUTE/AXI_ARADDR");
    sc_trace(tf, vta.m1_ARVALID, "5_COMPUTE/AXI_ARVALID");
    sc_trace(tf, vta.m1_ARREADY, "5_COMPUTE/AXI_ARREADY");
    sc_trace(tf, vta.m1_RVALID,  "5_COMPUTE/AXI_RVALID");
    sc_trace(tf, vta.m1_RREADY,  "5_COMPUTE/AXI_RREADY");
    sc_trace(tf, vta.m1_RDATA,   "5_COMPUTE/AXI_RDATA");

    // ==========================================
    // 6. STORE MODULE (Result Write)
    // ==========================================
    sc_trace(tf, vta.m2_AWADDR,  "6_STORE/AXI_AWADDR");
    sc_trace(tf, vta.m2_AWVALID, "6_STORE/AXI_AWVALID");
    sc_trace(tf, vta.m2_AWREADY, "6_STORE/AXI_AWREADY");
    sc_trace(tf, vta.m2_WDATA,   "6_STORE/AXI_WDATA");
    sc_trace(tf, vta.m2_WVALID,  "6_STORE/AXI_WVALID");
    sc_trace(tf, vta.m2_WREADY,  "6_STORE/AXI_WREADY");
    sc_trace(tf, vta.m2_WLAST,   "6_STORE/AXI_WLAST");
    sc_trace(tf, vta.m2_BVALID,  "6_STORE/AXI_BVALID");
    sc_trace(tf, vta.m2_BREADY,  "6_STORE/AXI_BREADY");

    // ==========================================
    // 7. PIPELINE DEPENDENCY QUEUES
    // ==========================================
    sc_trace(tf, vta.load_l2c_vld_sig,    "7_DEPENDENCIES/l2c_Load_Ready");
    sc_trace(tf, vta.compute_c2l_vld_sig, "7_DEPENDENCIES/c2l_Compute_Done");
    sc_trace(tf, vta.compute_c2s_vld_sig, "7_DEPENDENCIES/c2s_Compute_Ready");
    sc_trace(tf, vta.store_s2c_vld_sig,   "7_DEPENDENCIES/s2c_Store_Done");

    // Run simulation
    int ms = 0;
    while (!sc_end_of_simulation_invoked()) {
        sc_start(1, SC_MS);
        if (ms % 50 == 0) std::cout << "Simulated Time: " << sc_time_stamp() << std::endl;
        ms++;
    }
    std::cout << "\n======================================================\n";
    std::cout << "  SIMULATION FINISHED SUCCESSFULLY AT " << sc_time_stamp() << "\n";
    std::cout << "======================================================\n" << std::endl;
    sc_close_vcd_trace_file(tf);

    // --- SAVE DRAM BACK TO dummy_data.bin (for verify_output.py) ---
    {
        std::string dram_path = std::string(SOURCE_DIR) + "/data/models/dummy_data.bin";
        std::ofstream f(dram_path, std::ios::binary);
        if (f.is_open()) {
            f.write(reinterpret_cast<const char*>(vta.dram->memory_array.data()),
                    vta.dram->memory_array.size());
            std::cout << "[DRAM] Saved " << vta.dram->memory_array.size()/(1024*1024)
                      << " MB back to dummy_data.bin" << std::endl;
        }
    }

    return 0;
}
